# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "pip" # Use "pip" for Python projects
    directory: "/noteApp" # The folder where your requirements.txt is located
    schedule:
      interval: "weekly"
