name: Django CI

on:
  push:
    branches: [ "main", "devsecops-pipeline" ]
  pull_request:
    branches: [ "main", "devsecops-pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r noteApp/requirements.txt

    - name: Run tests
      working-directory: ./noteApp
      run: python manage.py test
