name: Django CI

on:
  push:
    branches: [ "main", "development-pipeline", "feature/*" ]
  pull_request:
    branches: [ "main", "development-pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r noteApp/requirements.txt

    - name: Run Django tests
      working-directory: ./noteApp
      run: python manage.py test

  sast-scan:
    name: SAST Scan (SonarCloud)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sca-scan:
    name: SCA Scan (Snyk)
    runs-on: ubuntu-latest
    needs: build

    permissions:
      security-events: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      # Node.js is needed to install the Snyk CLI
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: pip install -r noteApp/requirements.txt

      # Install the Snyk CLI tool directly
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Run the Snyk CLI command
      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        run: snyk test --file=noteApp/requirements.txt --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif